language: android
jdk: oraclejdk8

branches:
  only:
    - master
    - test-builds
    - /^v([0-9]+)\.([0-9]+).*$/

android:
  components:
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository

addons:
  apt:
    sources: deadsnakes
    packages: python3.7
  ssh_known_hosts: ssh.iitc.app

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: test-builds
      if: branch = test-builds
      env: BUILD_TYPE=test
    - stage: beta
      if: branch = master
      env: BUILD_TYPE=beta
    - stage: release
      if: NOT branch IN (test-builds, master)
      env: BUILD_TYPE=release

before_install:
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
  - bundle install --path vendor/bundle

before_script:
  - wget https://iitc.app/deploy/localbuildsettings.py

script: ./build.py $BUILD_TYPE

deploy:

  # deploy beta to google play
  - provider: script
    skip_cleanup: true
    script: ./fastlane/push.py
    on:
      branch: master

  # deploy release to google play
  - provider: script
    skip_cleanup: true
    script: ./fastlane/push.py
    on:
      tags: true