name: Build PR

# read-only repo token
# no access to secrets
on:
  pull_request:
    paths-ignore:
      - '!.github/**'

jobs:

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: error
          fail_on_error: true

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set env BUILD_TYPE
        run: |
            echo "BUILD_TYPE=test" >> "$GITHUB_ENV"

      - name: Download localbuildsettings.py
        run: wget https://iitc.app/deploy/localbuildsettings.py

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          only_changed: True

      - name: Run build.py
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: ./build.py $BUILD_TYPE

      - name: Save PR metadata
        run: |
          mv ./build/${{ env.BUILD_TYPE }} ./build/build
          mkdir -p ./build/.metadata
          echo ${{ github.event.number }} > ./build/.metadata/number
          echo ${{ github.event.pull_request.head.sha }} > ./build/.metadata/commit
          echo $( ls ./build/build/ | grep '.apk' ) > ./build/.metadata/apk_filename
          echo $( ls ./build/build/ | grep '.zip' ) > ./build/.metadata/zip_filename
          echo $(date -u +'%Y-%m-%d_%H-%M' -d"$(stat -c %y ./build/build/total-conversion-build.user.js)") > ./build/.metadata/buildstamp

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ./build/.metadata/
            ./build/build/
