name: Build IITC and push artifacts

on:
  push:
    branches:
      - master
      - "v[0-9]*.[0-9]*.[0-9]*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set env BUILD_TYPE and ARCHIVE_DIR (optional)
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            if [[ $BRANCH == 'master' ]]; then
                echo "BUILD_TYPE=beta" >> "$GITHUB_ENV"
                echo "ARCHIVE_DIR=beta_archive" >> "$GITHUB_ENV"
            else
                echo "BUILD_TYPE=release" >> "$GITHUB_ENV"
                echo "ARCHIVE_DIR=release_archive" >> "$GITHUB_ENV"
            fi
          else
              echo "BUILD_TYPE=test" >> "$GITHUB_ENV"
          fi

      - name: Download localbuildsettings.py
        run: wget https://iitc.app/deploy/localbuildsettings.py

      - name: Run build.py
        run: ./build.py $BUILD_TYPE
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}

      - name: Set env with artifacts
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "ARTIFACT_IITC_MOBILE=$( ls -d ./build/${{ env.BUILD_TYPE }}/* | grep '.apk' )" >> "$GITHUB_ENV"
          echo "ARTIFACT_IITC_ZIP=$( ls -d ./build/${{ env.BUILD_TYPE }}/* | grep '.zip' )" >> "$GITHUB_ENV"

      - name: Push artifacts to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: |
            ${{ env.ARTIFACT_IITC_MOBILE }}
            ${{ env.ARTIFACT_IITC_ZIP }}

      - name: Push build artifacts to website
        if: ${{ github.event_name == 'push' && secrets.WEBSITE_REPO }}
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "./build/${{ env.BUILD_TYPE }}/*"
          destination_repo: ${{ secrets.WEBSITE_REPO }}
          destination_folder: 'static/build/${{ env.ARCHIVE_DIR }}/1/'
          user_email: 'example@email.com'
          user_name: 'IITC Builds'
