name: Build IITC and push artifacts

on:
  push:
    branches:
      - master
      - "v[0-9]*.[0-9]*.[0-9]*"
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set env BUILD_TYPE and ARCHIVE_DIR (optional)
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            if [[ $BRANCH == 'master' ]]; then
                echo "BUILD_TYPE=beta" >> "$GITHUB_ENV"
                echo "ARCHIVE_DIR=beta_archive" >> "$GITHUB_ENV"
            else
                echo "BUILD_TYPE=release" >> "$GITHUB_ENV"
                echo "ARCHIVE_DIR=release_archive" >> "$GITHUB_ENV"
            fi
          else
              echo "BUILD_TYPE='test-builds'" >> "$GITHUB_ENV"
          fi

      - name: Download localbuildsettings.py
        run: wget https://iitc.app/deploy/localbuildsettings.py

      - name: Run build.py
        run: ./build.py $BUILD_TYPE

