name: After PR merging

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Send build artifacts to website
        env:
          WEBSITE_REPO: ${{ secrets.WEBSITE_REPO }}
        if: ${{ env.WEBSITE_REPO != '' }}
        run: |
          curl -X POST https://api.github.com/repos/${{ secrets.WEBSITE_REPO }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.API_TOKEN_GITHUB }} \
          --data '{"event_type": "delete_iitc_pr_build", "client_payload": { "repo": {"pr_number": "${{ github.event.number }}" }}'
