name: reviewdog

# read-only repo token
# no access to secrets
on:
  pull_request:
    paths-ignore:
      - '!.github/**'

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_on_error: true
