name: reviewdog

on:
  pull_request:

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: read
    
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_on_error: true
